global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using CloudCart.Application.Abstractions;
global using CloudCart.Contracts.Requests;
global using CloudCart.Contracts.Responses;
global using Microsoft.AspNetCore.Mvc;
